Converts mapbox-gl-circle to typescript
smithmicro/mapbox-gl-circle pull request #86
Opened 2020-01-28 16:23 UTC by gleite

Upgrades Mapbox GL JS from v.0.44.1 -> v.1.6.1
Upgrades Turf v.4.7.3 -> v.5.1.6

2020-12-04 16:57 UTC, gabrielcampos approved these changes

2021-12-19 13:45 UTC, RiatIO commented
Can we merge this pr please? @mblomdahl @carlba @ryanbaumann @dsperling

2022-10-14 09:53 UTC, mblomdahl requested changes
I love the idea of reworking this into Typescript, but I think we need to restore support for building and publishing this as NPM package, and also make sense of the thousands of changes by documenting commits before considering merging it. Please check out the commit granularity from previous feature PRs for examples of what we aimed at in the past: https://github.com/smithmicro/mapbox-gl-circle/pull/53/commits

Very nice job with the Typescript conversion @gleite! From my local testing most things seem to work very well. 🌟

2022-10-14 09:53 UTC, mblomdahl commented on Jenkinsfile
> -}
I think we should not remove the CI/CD functionality for building and publishing the package to NPM, but rather 1) reinstate Jenkins, or 2) transition our Continuous Integration to [GitHub Actions](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) workflow.

2022-10-14 09:53 UTC, mblomdahl commented on example/index.js
> -}, 2500);
As I recall, these Pittsburgh centered circles was very useful during development and testing some tricky corner cases. Now, with this PR, these are eliminated in favour of the GitHub Pages circles from `./index.html` centered around Stockholm (https://smithmicro.github.io/mapbox-gl-circle/). I think these clusters should be kept separately, in order to thoroughly test different scenarios.

2022-10-14 09:53 UTC, mblomdahl commented on LICENSE
> +Copyright (c) 2020, Smith Micro Software, Inc.
```suggestion
Copyright (c) 2017, Smith Micro Software, Inc.
```

Citing [U.S. Copyright Office](https://www.copyright.gov/help/faq/faq-duration.html):

> ## Do I have to renew my copyright?
> No. Works created on or after January 1, 1978, are not subject to renewal registration. As to works published or registered prior to January 1, 1978, renewal registration is optional after 28 years but does provide certain legal advantages. For information on how to file a renewal application as well as the legal benefit for doing so, see [Circular 15](https://www.copyright.gov/circs/circ15.pdf), Renewal of Copyright, and [Circular 15a](https://www.copyright.gov/circs/circ15a.pdf), Duration of Copyright.

2022-10-14 09:53 UTC, mblomdahl commented on Dockerfile
> +RUN npm install
Each of these statements will create a layer in for the container image that is subject to caching. I.e.

    COPY package.json /opt/mapbox-gl-circle/ ← layer N
    COPY index.html /opt/mapbox-gl-circle/ ← layer N+1
    COPY lib/main.ts /opt/mapbox-gl-circle/lib/ ← layer N+2
    COPY example/index.ts /opt/mapbox-gl-circle/example/ ← layer N+3
    RUN npm install ← layer N+4

When you change the execution order to run the most expensive step (`npm install`) last, it means that any line changed in the `index.html` file or `lib/main.ts` will force a complete rebuild of "layer N+4", this is probably not what we want. So it' propose reverting to running the install step directly after adding the `package.json`.

2022-10-14 09:53 UTC, mblomdahl commented on README.md
> -
The `npm run docs` step from the [Update README API Documentation](https://github.com/gleite-smsi/mapbox-gl-circle#update-readme-api-documentation) is broken with the changes in this PR. I see that you've written very neat and clear Typescript docs for the `MapboxCricle` public interface, so would it be possible to still generate a readable summary here? I looked at [this TypeDoc example](https://typedoc.org/example/classes/CancellablePromise.html) and it appeared promising to me.

2022-10-14 09:53 UTC, mblomdahl commented on index.html
> +<script src="bundle.js"></script>
This will break the [GitHub Pages feature](https://smithmicro.github.io/mapbox-gl-circle/), as you are referencing a source file produced during build time and also _`.gitignore`_'d.

2022-10-14 09:53 UTC, mblomdahl commented on package.json
> -  },
I think the engines constraint should be kept. It is useful information to keep folks in line with the current LTS (at least). I tested installing this with NPM 8 and Node versions 14, 16, and 18. No issues encountered, so let's set it to   14 ≤ Node ≤ 18 per [the current release schedule](https://github.com/nodejs/release#release-schedule).

2022-10-14 09:53 UTC, mblomdahl commented on lib/main.ts
> +}
To me, this change is overly difficult to review. Could you please split up this commit into multiple changes so that they can be interpreted by git? As you see here, now it's so vastly different that git basically says "one giant source file removed, one (unrelated) giant source file added". Basically, we should be able to break it down into:

1. Re-order object property names alphabetically per your auto-formatting tool (yields a lot of clutter)
2. Change naming convention for the event handlers from `/** @private */ _aPrivateMethod() {...}` → `private aPrivateMethod() {...}` (also adds a lot of clutter)
3. Move type hints from JSDoc to Typescript, `/** @param {string} event */` → `event: string` (more clutter)
4. Re-order the methods of `MapboxCircle` class (more clutter)
5. Additional functional changes (if any?!)
6. `package.json` and `tsconfig.json` config updates with some notes on how the new script commands are intended to function

2022-10-23 13:58 UTC, mblomdahl commented on Jenkinsfile
> -}
Fixed with #93, #94, and #98.

2024-03-11 22:21 UTC, mblomdahl commented
This will be replaced by the typing effort on #103.

2024-03-11 22:21 UTC, closed without merging